import { createHash } from "node:crypto";

export interface RenderedInstallAsset {
  path: string;
  checksum: string;
  content: string;
}

export interface ManagedNginxConfigOptions {
  controlPlaneHost?: string;
  wildcardBaseDomain?: string;
  apiPort?: number;
  path?: string;
  clientMaxBodySize?: string;
}

export interface ManagedNginxConfig extends RenderedInstallAsset {
  controlPlaneHost?: string;
  wildcardBaseDomain?: string;
  previewHostPattern?: string;
  apiPort: number;
}

export interface SiteFlowEnvFileOptions {
  apiPort: number;
  artifactRoot: string;
  publicScheme: "http" | "https";
  version: string;
  image: string;
  baseDomain?: string;
  path?: string;
}

export interface ComposeFileOptions extends SiteFlowEnvFileOptions {
  dataDir: string;
  configDir: string;
  databaseName?: string;
  databaseUser?: string;
  postgresImage?: string;
  path?: string;
}

export interface SystemdUnitOptions {
  composeFile: string;
  workingDirectory: string;
  unitName?: string;
  path?: string;
}

function checksum(content: string) {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}

function renderedAsset(path: string, content: string): RenderedInstallAsset {
  return {
    path,
    checksum: checksum(content),
    content
  };
}

export function normalizeDnsName(value: string, label = "Domain") {
  const normalized = value.trim().toLowerCase().replace(/^\*\./, "");

  if (!normalized) {
    throw new Error(`${label} is required.`);
  }

  if (!/^[a-z0-9.-]+$/.test(normalized) || !normalized.includes(".")) {
    throw new Error(`${label} must be a DNS name such as w33d.xyz.`);
  }

  const labels = normalized.split(".");

  for (const part of labels) {
    if (!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(part)) {
      throw new Error(`${label} contains an invalid DNS label: ${part || "<empty>"}.`);
    }
  }

  const tld = labels[labels.length - 1];

  if (!/^[a-z]{2,63}$/.test(tld)) {
    throw new Error(`${label} must end with a public DNS suffix such as .xyz.`);
  }

  return normalized;
}

function normalizeApiPort(value: number | undefined) {
  const port = value ?? 8787;

  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error("API port must be an integer between 1 and 65535.");
  }

  return port;
}

function proxyHeaders() {
  return [
    "        proxy_http_version 1.1;",
    "        proxy_set_header Host $host;",
    "        proxy_set_header X-Forwarded-Host $host;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header Connection \"\";"
  ].join("\n");
}

function proxyLocation() {
  return [
    "    location / {",
    "        proxy_pass http://siteflow_api;",
    proxyHeaders(),
    "    }"
  ].join("\n");
}

export function renderManagedNginxConfig(options: ManagedNginxConfigOptions): ManagedNginxConfig {
  const controlPlaneHost = options.controlPlaneHost ? normalizeDnsName(options.controlPlaneHost, "Control-plane domain") : undefined;
  const wildcardBaseDomain = options.wildcardBaseDomain ? normalizeDnsName(options.wildcardBaseDomain, "Wildcard base domain") : undefined;
  const apiPort = normalizeApiPort(options.apiPort);
  const clientMaxBodySize = options.clientMaxBodySize ?? "128m";

  if (!controlPlaneHost && !wildcardBaseDomain) {
    throw new Error("Managed Nginx requires a control-plane domain or wildcard base domain.");
  }

  const blocks = [
    "# Generated by SiteFlow. Do not edit manually.",
    "# Source: siteflow install render-config",
    "",
    "upstream siteflow_api {",
    `    server 127.0.0.1:${apiPort};`,
    "    keepalive 32;",
    "}"
  ];

  if (controlPlaneHost) {
    blocks.push(
      "",
      "server {",
      "    listen 80;",
      `    server_name ${controlPlaneHost};`,
      "",
      `    client_max_body_size ${clientMaxBodySize};`,
      "",
      proxyLocation(),
      "}"
    );
  }

  if (wildcardBaseDomain) {
    blocks.push(
      "",
      "server {",
      "    listen 80;",
      `    server_name *.${wildcardBaseDomain};`,
      "",
      `    client_max_body_size ${clientMaxBodySize};`,
      "",
      "    location = /api {",
      "        return 404;",
      "    }",
      "",
      "    location ^~ /api/ {",
      "        return 404;",
      "    }",
      "",
      "    location = /healthz {",
      "        return 404;",
      "    }",
      "",
      proxyLocation(),
      "}"
    );
  }

  const content = `${blocks.join("\n")}\n`;

  return {
    ...renderedAsset(options.path ?? "/etc/nginx/sites-available/siteflow.conf", content),
    controlPlaneHost,
    wildcardBaseDomain,
    previewHostPattern: wildcardBaseDomain ? `*.${wildcardBaseDomain}` : undefined,
    apiPort
  };
}

export function renderSiteFlowEnvFile(options: SiteFlowEnvFileOptions): RenderedInstallAsset {
  const lines = [
    `SITEFLOW_VERSION=${options.version}`,
    `SITEFLOW_IMAGE=${options.image}`,
    `SITEFLOW_API_PORT=${options.apiPort}`,
    `SITEFLOW_ARTIFACT_ROOT=${options.artifactRoot}`,
    `SITEFLOW_PUBLIC_SCHEME=${options.publicScheme}`
  ];

  if (options.baseDomain) {
    lines.push(`SITEFLOW_BASE_DOMAIN=${normalizeDnsName(options.baseDomain, "Wildcard base domain")}`);
  }

  return renderedAsset(options.path ?? "/etc/siteflow/siteflow.env", `${lines.join("\n")}\n`);
}

export function renderComposeFile(options: ComposeFileOptions): RenderedInstallAsset {
  const databaseName = options.databaseName ?? "siteflow";
  const databaseUser = options.databaseUser ?? "siteflow";
  const postgresImage = options.postgresImage ?? "postgres:16-alpine";
  const postgresData = `${options.dataDir}/postgres`;
  const apiPort = normalizeApiPort(options.apiPort);
  const envLines = [
    `      SITEFLOW_API_PORT: "${apiPort}"`,
    `      SITEFLOW_ARTIFACT_ROOT: "${options.artifactRoot}"`,
    `      SITEFLOW_PUBLIC_SCHEME: "${options.publicScheme}"`
  ];

  if (options.baseDomain) {
    envLines.push(`      SITEFLOW_BASE_DOMAIN: "${normalizeDnsName(options.baseDomain, "Wildcard base domain")}"`);
  }

  const content = [
    "# Generated by SiteFlow. Do not edit manually.",
    "services:",
    "  postgres:",
    `    image: ${postgresImage}`,
    "    restart: unless-stopped",
    "    environment:",
    `      POSTGRES_DB: ${databaseName}`,
    `      POSTGRES_USER: ${databaseUser}`,
    "      POSTGRES_PASSWORD_FILE: /run/secrets/siteflow_postgres_password",
    "    volumes:",
    `      - ${postgresData}:/var/lib/postgresql/data`,
    "    secrets:",
    "      - siteflow_postgres_password",
    "",
    "  api:",
    `    image: ${options.image}`,
    "    restart: unless-stopped",
    "    depends_on:",
    "      - postgres",
    "    environment:",
    ...envLines,
    "      SITEFLOW_API_TOKEN_FILE: /run/secrets/siteflow_api_token",
    "      SITEFLOW_POSTGRES_PASSWORD_FILE: /run/secrets/siteflow_postgres_password",
    "    command:",
    "      - sh",
    "      - -ec",
    "      - |",
    "        export SITEFLOW_API_TOKEN=\"$(cat /run/secrets/siteflow_api_token)\"",
    `        export DATABASE_URL=\"postgres://${databaseUser}:$(cat /run/secrets/siteflow_postgres_password)@postgres:5432/${databaseName}\"`,
    "        exec node dist-server/server/index.js",
    "    ports:",
    `      - \"127.0.0.1:${apiPort}:${apiPort}\"`,
    "    volumes:",
    `      - ${options.artifactRoot}:${options.artifactRoot}`,
    "    secrets:",
    "      - siteflow_api_token",
    "      - siteflow_postgres_password",
    "",
    "secrets:",
    "  siteflow_api_token:",
    `    file: ${options.configDir}/secrets/api-token.secret`,
    "  siteflow_postgres_password:",
    `    file: ${options.configDir}/secrets/postgres-password.secret`
  ].join("\n");

  return renderedAsset(options.path ?? "/opt/siteflow/compose.yaml", `${content}\n`);
}

export function renderSystemdUnit(options: SystemdUnitOptions): RenderedInstallAsset {
  const unitName = options.unitName ?? "siteflow.service";
  const content = [
    "# Generated by SiteFlow. Do not edit manually.",
    "[Unit]",
    "Description=SiteFlow single-host stack",
    "Requires=docker.service",
    "After=docker.service network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=oneshot",
    "RemainAfterExit=yes",
    `WorkingDirectory=${options.workingDirectory}`,
    `ExecStart=/usr/bin/docker compose -f ${options.composeFile} up -d`,
    `ExecStop=/usr/bin/docker compose -f ${options.composeFile} down`,
    "TimeoutStartSec=0",
    "",
    "[Install]",
    "WantedBy=multi-user.target"
  ].join("\n");

  return renderedAsset(options.path ?? `/etc/systemd/system/${unitName}`, `${content}\n`);
}
