export interface ForbiddenTrackedReleasePathRule {
  reason: string;
}

export interface ForbiddenTrackedReleasePathPrefix extends ForbiddenTrackedReleasePathRule {
  prefix: string;
}

export interface ForbiddenTrackedReleasePathFile extends ForbiddenTrackedReleasePathRule {
  path: string;
}

export interface ForbiddenTrackedReleasePathPattern extends ForbiddenTrackedReleasePathRule {
  pattern: RegExp;
  label: string;
}

export interface ForbiddenTrackedReleasePathFinding {
  path: string;
  reason: string;
}

export interface AllowedTrackedReleasePathFile {
  path: string;
  reason: string;
}

export interface IndexOnlyReleaseSourceCleanupCommand {
  command: "git";
  args: string[];
  display: string;
  pathspecs: string[];
  modifiesGitIndex: true;
  removesWorkingTreeFiles: false;
  requiresReview: true;
  notes: string[];
}

export const forbiddenTrackedReleasePathPrefixes: ForbiddenTrackedReleasePathPrefix[] = [
  { prefix: "node_modules/", reason: "dependency installs must be reconstructed by npm ci" },
  { prefix: "dist/", reason: "frontend build output must be generated by npm run build" },
  { prefix: "dist-cli/", reason: "CLI build output must be generated by npm run build" },
  { prefix: "dist-server/", reason: "server build output must be generated by npm run build" },
  { prefix: "dist-worker/", reason: "worker build output must be generated by npm run build" },
  { prefix: "coverage/", reason: "coverage output is test runtime state" },
  { prefix: "playwright-report/", reason: "Playwright report output is test runtime state" },
  { prefix: "test-results/", reason: "Playwright trace output is test runtime state" },
  { prefix: "evidence/", reason: "release evidence output must be archived per release, not committed as source" },
  { prefix: ".vite/", reason: "Vite cache output is local runtime state" },
  { prefix: ".workflow/", reason: "workflow scratch state must not be part of the release source" }
];

export const forbiddenTrackedReleasePathFiles: ForbiddenTrackedReleasePathFile[] = [
  { path: ".env", reason: "environment files must not be committed" }
];

export const allowedTrackedReleasePathFiles: AllowedTrackedReleasePathFile[] = [
  { path: ".env.example", reason: "documented environment template is safe to commit" }
];

export const forbiddenTrackedReleasePathPatterns: ForbiddenTrackedReleasePathPattern[] = [
  { pattern: /^\.env\./, label: ".env.*", reason: "environment files must not be committed" },
  {
    pattern: /^release-artifact-manifest.*\.json$/,
    label: "release-artifact-manifest*.json",
    reason: "local artifact manifests must be regenerated for each release"
  },
  {
    pattern: /^release-image-evidence.*\.json$/,
    label: "release-image-evidence*.json",
    reason: "release image evidence must be collected from the publishing workflow"
  },
  {
    pattern: /^release-evidence.*\.json$/,
    label: "release-evidence*.json",
    reason: "release evidence bundles must be collected and archived per release, not committed as source"
  },
  {
    pattern: /^release-post-promotion-evidence.*\.json$/,
    label: "release-post-promotion-evidence*.json",
    reason: "post-promotion evidence must be collected from the target release, not committed as source"
  },
  {
    pattern: /^release-source-cleanup-plan.*\.json$/,
    label: "release-source-cleanup-plan*.json",
    reason: "release source cleanup plans are local review artifacts"
  },
  {
    pattern: /^release-commit-readiness-plan.*\.json$/,
    label: "release-commit-readiness-plan*.json",
    reason: "release commit readiness plans are local review artifacts"
  },
  {
    pattern: /^npm-debug\.log.*$/,
    label: "npm-debug.log*",
    reason: "npm debug logs are local install/runtime artifacts"
  }
];

export function normalizeTrackedReleasePath(filePath: string) {
  return filePath.trim().replace(/\\/g, "/");
}

export function forbiddenTrackedPathReason(filePath: string) {
  const normalized = normalizeTrackedReleasePath(filePath);
  const allowed = allowedTrackedReleasePathFiles.find((entry) => normalized === entry.path);

  if (allowed) {
    return undefined;
  }

  const exact = forbiddenTrackedReleasePathFiles.find((entry) => normalized === entry.path);

  if (exact) {
    return exact.reason;
  }

  const prefix = forbiddenTrackedReleasePathPrefixes.find((entry) => normalized.startsWith(entry.prefix));

  if (prefix) {
    return prefix.reason;
  }

  const pattern = forbiddenTrackedReleasePathPatterns.find((entry) => entry.pattern.test(normalized));

  return pattern?.reason;
}

export function findForbiddenTrackedReleasePaths(filePaths: Iterable<string>) {
  const findings: ForbiddenTrackedReleasePathFinding[] = [];

  for (const filePath of filePaths) {
    const normalized = normalizeTrackedReleasePath(filePath);

    if (!normalized) {
      continue;
    }

    const reason = forbiddenTrackedPathReason(normalized);

    if (reason) {
      findings.push({ path: normalized, reason });
    }
  }

  return findings;
}

function shellQuotePathspec(pathspec: string) {
  if (/^[A-Za-z0-9._/@:-]+$/.test(pathspec)) {
    return pathspec;
  }

  return `"${pathspec.replace(/(["`$\\])/g, "\\$1")}"`;
}

function indexOnlyCleanupPathspecs(findings: ForbiddenTrackedReleasePathFinding[]) {
  const pathspecs = new Set<string>();
  const normalizedFindings = findings.map((finding) => finding.path);

  for (const prefix of forbiddenTrackedReleasePathPrefixes) {
    if (normalizedFindings.some((filePath) => filePath.startsWith(prefix.prefix))) {
      pathspecs.add(prefix.prefix.replace(/\/$/, ""));
    }
  }

  for (const exact of forbiddenTrackedReleasePathFiles) {
    if (normalizedFindings.includes(exact.path)) {
      pathspecs.add(exact.path);
    }
  }

  for (const finding of normalizedFindings) {
    const coveredByPrefix = forbiddenTrackedReleasePathPrefixes.some((entry) => finding.startsWith(entry.prefix));
    const coveredByExact = forbiddenTrackedReleasePathFiles.some((entry) => finding === entry.path);

    if (!coveredByPrefix && !coveredByExact) {
      pathspecs.add(finding);
    }
  }

  return [...pathspecs].sort((left, right) => left.localeCompare(right));
}

export function suggestedIndexOnlyReleaseSourceCleanupCommand(
  findings: ForbiddenTrackedReleasePathFinding[]
): IndexOnlyReleaseSourceCleanupCommand | null {
  if (findings.length === 0) {
    return null;
  }

  const pathspecs = indexOnlyCleanupPathspecs(findings);
  const args = ["rm", "--cached", "-r", "--", ...pathspecs];

  return {
    command: "git",
    args,
    display: ["git", ...args.map(shellQuotePathspec)].join(" "),
    pathspecs,
    modifiesGitIndex: true,
    removesWorkingTreeFiles: false,
    requiresReview: true,
    notes: [
      "This is an index-only cleanup plan; it removes reviewed paths from Git tracking without deleting local files.",
      "Run it only after reviewing pathList and preserving unrelated worktree changes.",
      "Commit the cleanup separately, then rerun release:source:check and siteflow release-gate."
    ]
  };
}

export function releaseSourceTreePolicyDetails() {
  return {
    allowedFiles: allowedTrackedReleasePathFiles.map((entry) => entry.path),
    forbiddenPrefixes: forbiddenTrackedReleasePathPrefixes.map((entry) => entry.prefix),
    forbiddenFiles: forbiddenTrackedReleasePathFiles.map((entry) => entry.path),
    forbiddenPatterns: forbiddenTrackedReleasePathPatterns.map((entry) => entry.label)
  };
}
